sudo: false
dist: trusty

language: php

notifications:
  slack:
    secure: JwqSRPsrDz6NpARk2Dv58MSvbPO/MEfIW2onXe5GDTHwGCTm67cmfCjJrrE2zQLt4UXbF0t/SE/zp9GZ6NAm8wQNauiXAdWxEnAgz/JjI+ubHhZptDmAG1+aALBQr6tV5EiJ9R6MqEbLekCvCB2pn0xNZZCOQTmY9F8xwkaJPgX+ubwwonoKJQ7txd8uKyfCn1b003f218n1RGagP6iUSk1PcodO7lA9WZwy1MJIp9W7/EsN6Z+xANyqkytnGrxXA/zqgf82cVBx55VdUDdKL/SSIgmovM2WptjsyMMDGqnMeGbnoskl1DmPvbqV9RXjU3qXlNZ1NT52iBZxLvVqRpAlwZrxQQer/f2/WGGo7nwV62zgDgWb0dYsGN6d7k1Ry0Pn3NZ9bnaY1b87gF3eSwWuj5VM7asm2weK5WUYYJTDCwLsWJ6yRvkaR7x1NQvWQmARmj0JpvyUk+pVUBtUImTvI1megn+67UlCtDbegRufa/2kK9VOmnRuYa3qJ6bManXe0mFQhOpxvGnkjVi8V+dSsNm1X6qa2ulczJxrU3IiCNfpokpJIaLhM4TokAnNF14AbEUimqlVXfFQJyRkaIrc9IL39K4Ft6OhbotKSYXSiK5YjPYFlSL1tij4oa4nPv5Q3+Mqn6+ChJQpCheZJFE1AkxTHmE1OUrBmlVc0Ok=
  email:
    on_success: always
    on_failure: always

branches:
  only:
    - master
    - dev

cache:
  directories:
    - $HOME/.composer/cache

stages:
  - name: test
  - name: 🚀 deployment
    if: branch = "master"

jobs:
  fast_finish: true
  include:
    - php: 7.3
      #env: WP_VERSION=latest WP_MULTISITE=1 WPSNIFF=1
      env: WP_VERSION=latest WP_MULTISITE=1
    - php: 7.0
      env: WP_VERSION=5.0
    - php: 5.6
      env: WP_VERSION=4.4
    - stage: 🚀 deployment
      name: "Deploy to WordPress"
      php: 7.3
      env: WP_VERSION=latest
      deploy:
        provider: script
        skip_cleanup: true
        script: bash ./bin/deploy.sh
        on:
          php: 7.3
          branch: master

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION false $CHEETAHO_API_KEY
      composer global require "phpunit/phpunit=4.8.*|5.7.*"
    fi
  - |
    if [[ "$WPSNIFF" == "1" ]] ; then
      composer global require wp-coding-standards/wpcs dealerdirect/phpcodesniffer-composer-installer
      phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs
    fi

script:
  - if [[ "$WPSNIFF" == "1" ]]; then phpcs --standard=phpcs.ruleset.xml --extensions=php .; fi
  - phpunit
env:
  global:
  - secure: WzV1pZggMqGHdFpPKmKqs2NXIMpGmdB6AfvXzyEoMAEkF+1apFU3qBoPHlP5wgHWKJWhBEw63KEuue7RsdTrm1pshDkFjsiSYNiU83m22YHoiI1mRLBerANOX03R7arWiwvvXxNFH+ll4KGV1LUiz2td5C1EW2ePIARPOh981uUHKj5bMgcld5KtYWwk1MhDrBC+6YGHow2D6zpW4LgSM9JKiPOwRE5YOnuf9YIaT9SZYO4ufrOkXoVxP8dT30aFBfR8FYPZygDqhnueU/OY/fEct3tQU89YdChZZ5eKF5aiehYZxNxklKq3sqg/E1OFzyGJ7dPk3dwqFROsflaVb/1U2EOjV58CZ6vejUhl/eypLFZQPTNgjmjX/V2kznuxr/krKLQ6Qy+1abY/W5CuLyhXcZYls0oTb5OrnpWYfKQzHDA50j+Y1VqEjS3ToS+FxEIKY6kPcDarHhCK8aVFi5vBfu2hW6vwC3Fw0uk+7rnGYZtEsz7oSIWyaPrkMPUZBkYswxv5hUqNdtIgw44etZISSy96a57+gl+Nz2eMSdxurIdFxQ5SGQZT91rN8WmI2hhb5eBb697wmS7mcjKobb+TZuc5up5oCzS+ov+le5cPAfgDvUDhuu5vE43uypdOzU/sYV4B2Mg7WhI4MouwlegGPTT8fR0zEAlm2sOxDVk=
  - secure: hTP3yZXCZ6Eo0ZqROcCNyCVs5+diypWhwkDC4LQ4V5/8f/wd44+RPqum+aXfHh0WoAC2NeYpsOgrZ/t/gMdcM+RjdovfpwGyeAqjKI0SZ5HgErn04Y6fjVQM1UT635TYtMo8DWMiq6/htBnvdOZ4gGssmHgjqyqXa1Ia/IOc7/YomjJNZ/PsexXsI3WA589meQhbNAc4qeiu3xaEqo02FnKuxVq/fVykbheGHq9MKnJiEBcW3wXZIWA9rj9i5v9/5pc72RWdwoKVsG6Z1EVdVneVllBZelXfn+OpPlZJFlG1w33km8y/VQSj5gX/f8faOwwDADWykFfy4xPOueO0cibKDHwkG2kLwQanbIOsOp3tNnS5jHv3oPyWmUNar0wr8cEWfP5Xx59VolKg3UhSOoblj9lMwA+4rGthpgPOBmhXH5mq1KWs+BghnfnfRujNzTBhqbt2owVO34z6GdFBqzIfcE4H1cOBreZKJjsIfRoN0bmoPHOxpbVqo9LJuwfbFkQCwAqCaKU4nSJ+s0NpjY7fX17WaE+J8kseyza3kyY3nx5qmsr5IwQgXQRbykwnoui+F+1q6RjTyT3ggRurghNmiDEGDU5Vqm9Kz2kxubwyJxUva2znBR5wX/dTbjnHPSAktIXSXr5Sr1/wp+vgufjplDw8a4RMzalpuB1ayKM=